Traceback (most recent call last):
  File "/Users/badri/.vscode/extensions/ms-python.python-2022.4.0/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-U', 'ipykernel', '/var/folders/bv/1l_zzhtd3mz045wm7s5mnpdm0000gn/T/tmp-2830634sF1KeSddVs.log']' returned non-zero exit status 1.
